name: Linter check and SonarCloud coverage check

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  Linter:
    name: Lint and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Run linter
        run: make lint

  Sonar:
    name: SonarCloud
    runs-on: ubuntu-latest
    needs: Linters
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: npm install

      - name: Test and coverage
        run: npm run test:coverage

      - name: Sonar Scan
        uses: SonarSource/sonarqube-scan-action@v7
        env:
          SONAR_TOKEN: ${{ secrets.SONARCLOUD_TOKEN }}
        args: >
          -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info



# name: Build
# on:
#  push:
#    branches:
#      - main
#  pull_request:
#    types: [opened, synchronize, reopened]
# jobs:
#   sonarqube:
#     name: SonarQube
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v6
#         with:
#           fetch-depth: 0 

#       - name: Install dependencies
#         run: npm install

#       - name: Test and coverage
#         run: npm run test:coverage

#       # - name: Log
#       #   run: |
#       #     ls -l coverage/lcov.info
#       #     head -n 10 coverage/lcov.info

#       - name: Sonar Scan
#         uses: SonarSource/sonarqube-scan-action@v7
#         env:
#           SONAR_TOKEN: ${{ secrets. SONARCLOUD_TOKEN }}
#         args: >
#           -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info