name: Build
on:
 push:
   branches:
     - main
 pull_request:
   types: [opened, synchronize, reopened]
jobs:
  sonarqube:
    name: SonarQube
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0 

      - name: Install dependencies
        run: npm install

      - name: Test and coverage
        run: npm run test:coverage

      - name: log
        run: |
          ls -l coverage/lcov.info
          head -n 10 coverage/lcov.info

      - name: Sonar Scan
        uses: SonarSource/sonarqube-scan-action@v7
        env:
          SONAR_TOKEN: ${{ secrets. SONARCLOUD_TOKEN }}
        args: >
          -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info


# name: SonarCloud Scan
# on: 
#   push:
#     branches:
#       - main 

# jobs: 
#   build:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v4
#         with:
#           fetch-depth: 0

#       - name: Install dependencies
#         run: npm install

#       - name: Run jest coverage tests
#         run: npm run test:coverage
      
#       - name: SonarCloud Scan
#         uses: SonarSource/sonarcloud-github-action@master
#         env:
#           SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
#           SONAR_HOST_URL: https://sonarcloud.io
#         with:
#           args: >
#             -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info